version: "3.9"

services:
  minio:
    container_name: RussianSpotify.API.MinioStorage
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=russianSpotifyMinio
      - MINIO_ROOT_PASSWORD=russianSpotifyMinioPassword
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - russianspotify_network

  postgres_db:
    image: postgres:16
    container_name: RussianSpotify.API.PostgresSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RussianSpotify.API.Data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - russianspotify_network

  redis:
    container_name: RussianSpotify.API.Redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - russianspotify_network

  rabbitmq:
    container_name: Russian.Spotify.API.RabbitMQ
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - russianspotify_network
  
  main_project:
    build:
      context: .
      dockerfile: RussianSpotify.API.WEB/Dockerfile
    image: karantuligor/russian-spotify-backend
    container_name: RussianSpotify.API.WEB
    depends_on:
      - redis
      - postgres_db
      - minio
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=root;Host=postgres_db;Port=5432;Database=RussianSpotify.API.Data"
      RedisOptions__ConnectionString: "redis:6379"
      EmailSettings__FromName: "RussianSpotify"
      EmailSettings__EmailAddress: "s1chess@yandex.ru"
      EmailSettings__Password: "qsmylcfruascxvhi"
      EmailSettings__SMTPServerHost: "smtp.yandex.ru"
      EmailSettings__SMTPServerPort: "465"
      RabbitMq__Host: "rabbitmq"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      RedirectUrl: "http://176.57.208.209:3000"
      GrpcOptions__Services__0__Name: "File"
      GrpcOptions__Services__0__ServerUri: "http://files_service:81"
    ports:
      - "80:80"
    networks:
      - russianspotify_network

  files_service:
    build:
      context: .
      dockerfile: RussianSpotify.API.Files/Dockerfile
    image: karantuligor/russian-spotify-files-service
    container_name: RussianSpotify.API.Files
    depends_on:
      - postgres_db
      - minio
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MinioOptions__MinioClient: "RussianSpotify"
      MinioOptions__AccessKey: "russianSpotifyMinio"
      MinioOptions__SecretKey: "russianSpotifyMinioPassword"
      MinioOptions__ServiceUrl: "minio:9000"
      MinioOptions__BucketName: "russian-spotify"
      MinioOptions__TempBucketName: "russian-spotify-temp"
      RedisOptions__ConnectionString: "redis:6379"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      DbContextOptions__ConnectionString: "User ID=postgres;Password=root;Host=postgres_db;Port=5432;Database=RussianSpotify.API.Files.Data"
      KestrelOptions__Options__0__EndpointType: Rest
      KestrelOptions__Options__0__Port: 5111
      KestrelOptions__Options__1__EndpointType: Grpc
      KestrelOptions__Options__1__Port: 5112
    ports:
      - "82:80"
      - "81:81"
    networks:
      - russianspotify_network
  
  chat_message_saver:
    build:
      context: .
      dockerfile: RussianSpotify.API.ChatMessageSaver/Dockerfile
    image: karantuligor/russian-spotify-chat_message_saver
    container_name: RussianSpotify.API.ChatMessageSaver
    depends_on:
      - redis
      - postgres_db
      - minio
      - rabbitmq
      - main_project
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=root;Host=postgres_db;Port=5432;Database=RussianSpotify.API.Data"
      RabbitMq__Host: "rabbitmq"
    networks:
      - russianspotify_network

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:

networks:
  russianspotify_network:
    driver: bridge
