version: "3.9"

services:
  minio:
    container_name: russianspotify-api-minio-storage
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=russianSpotifyMinio
      - MINIO_ROOT_PASSWORD=russianSpotifyMinioPassword
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - russianspotify-network

  postgres-db:
    image: postgres:16
    container_name: russianspotify-api-postgres-sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: russianspotify-api-data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - russianspotify-network

  subscription-postgres-db:
    image: postgres:16
    container_name: russian-spotify-subscription-postgres-sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: russianspotify-subscription-api-data
    ports:
      - "5431:5432"
    volumes:
      - postgres_subscription_data:/var/lib/postgresql/data
    networks:
      - russianspotify-network

  payment-postgres-db:
    image: postgres:16
    container_name: russian-spotify-payment-postgres-sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: russianspotify-payment-api-data
    ports:
      - "5430:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    networks:
      - russianspotify-network


  redis:
    container_name: russianspotify-api-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - russianspotify-network

  rabbitmq:
    container_name: russianspotify-api-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - russianspotify-network

  main-project:
    build:
      context: .
      dockerfile: RussianSpotify.API.WEB/Dockerfile
    image: karantuligor/russian-spotify-backend
    container_name: russianspotify-api-web
    depends_on:
      - redis
      - postgres-db
      - minio
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ExternalSubscriptionDbContext: "User ID=postgres;Password=root;Host=subscription-postgres-db;Port=5432;Database=russianspotify-subscription-api-data"
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=root;Host=postgres-db;Port=5432;Database=russianspotify-api-data"
      RedisOptions__ConnectionString: "redis:6379"
      EmailSettings__FromName: "RussianSpotify"
      EmailSettings__EmailAddress: "s1chess@yandex.ru"
      EmailSettings__Password: "qsmylcfruascxvhi"
      EmailSettings__SMTPServerHost: "smtp.yandex.ru"
      EmailSettings__SMTPServerPort: "465"
      RabbitMq__Host: "rabbitmq"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      RedirectUrl: "http://176.57.208.209:3000"
      GrpcOptions__Services__0__Name: "File"
      GrpcOptions__Services__0__ServerUri: "http://files-service:81"
      GrpcOptions__Services__1__Name: "Payment"
      GrpcOptions__Services__1__ServerUri: "http://payment-service:5116"
    ports:
      - "80:80"
    networks:
      - russianspotify-network

  files-service:
    build:
      context: .
      dockerfile: RussianSpotify.API.Files/Dockerfile
    image: karantuligor/russian-spotify-files-service
    container_name: russianspotify-api-files
    depends_on:
      - postgres-db
      - minio
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MinioOptions__MinioClient: "RussianSpotify"
      MinioOptions__AccessKey: "russianSpotifyMinio"
      MinioOptions__SecretKey: "russianSpotifyMinioPassword"
      MinioOptions__ServiceUrl: "minio:9000"
      MinioOptions__BucketName: "russian-spotify"
      MinioOptions__TempBucketName: "russian-spotify-temp"
      RedisOptions__ConnectionString: "redis:6379"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      DbContextOptions__ConnectionString: "User ID=postgres;Password=root;Host=postgres-db;Port=5432;Database=russianspotify-api-files-data"
      KestrelOptions__Options__0__EndpointType: Rest
      KestrelOptions__Options__0__Port: 5111
      KestrelOptions__Options__1__EndpointType: Grpc
      KestrelOptions__Options__1__Port: 5112
    ports:
      - "82:80"
      - "81:81"
    networks:
      - russianspotify-network

  chat-message-saver:
    build:
      context: .
      dockerfile: RussianSpotify.API.ChatMessageSaver/Dockerfile
    image: karantuligor/russian-spotify-chat-message-saver
    container_name: russianspotify-api-chat-message-saver
    depends_on:
      - redis
      - postgres-db
      - minio
      - rabbitmq
      - main-project
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=root;Host=postgres-db;Port=5432;Database=russianspotify-api-data"
      RabbitMq__Host: "rabbitmq"
    networks:
      - russianspotify-network

  subscription-service:
    build:
      context: .
      dockerfile: RussianSpotify.API.SubscriptionService/Dockerfile
    image: karantuligor/russian-spotify-subscription-service
    container_name: russian-spotify-subscription-service
    depends_on:
      - redis
      - rabbitmq
      - subscription-postgres-db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DbContextOptions__ConnectionString: "User ID=postgres;Password=root;Host=subscription-postgres-db;Port=5432;Database=russianspotify-subscription-api-data"
      RabbitMqOptions__Host: "rabbitmq"
      RedisOptions__ConnectionString: "redis:6379"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      KestrelOptions__Options__0__EndpointType: Rest
      KestrelOptions__Options__0__Port: 5113
      KestrelOptions__Options__1__EndpointType: Grpc
      KestrelOptions__Options__1__Port: 5114
    ports:
      - "83:5113"
      - "84:5114"
    networks:
      - russianspotify-network

  payment-service:
    build:
      context: .
      dockerfile: RussianSpotify.API.PaymentService/Dockerfile
    image: karantuligor/russian-spotify-payment-service
    container_name: russian-spotify-payment-service
    depends_on:
      - redis
      - rabbitmq
      - payment-postgres-db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DbContextOptions__ConnectionString: "User ID=postgres;Password=root;Host=payment-postgres-db;Port=5432;Database=russianspotify-payment-api-data"
      RabbitMqOptions__Host: "rabbitmq"
      RedisOptions__ConnectionString: "redis:6379"
      JWT__ValidAudience: "176.57.208.209"
      JWT__ValidIssuer: "176.57.208.209"
      JWT__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      KestrelOptions__Options__0__EndpointType: Rest
      KestrelOptions__Options__0__Port: 5115
      KestrelOptions__Options__1__EndpointType: Grpc
      KestrelOptions__Options__1__Port: 5116
    ports:
      - "85:5115"
      - "86:5116"
    networks:
      - russianspotify-network


volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:
  postgres_subscription_data:
  postgres_payment_data:

networks:
  russianspotify-network:
    driver: bridge