version: "3.9"

services:
  minio:
    container_name: RussianSpotify.API.MinioStorage
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=russianSpotifyMinio
      - MINIO_ROOT_PASSWORD=russianSpotifyMinioPassword
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - russianspotify_network

  postgres_db:
    image: postgres:16
    container_name: RussianSpotify.API.PostgresSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RussianSpotify.API.Data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - russianspotify_network

  redis:
    container_name: RussianSpotify.API.Redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - russianspotify_network
  
  main_project:
    build:
      context: .
      dockerfile: RussianSpotify.API.WEB/Dockerfile
    image: irekkkarimov/russian-spotify-backend
    container_name: RussianSpotify.API.UI
    depends_on:
      - redis
      - postgres_db
      - minio
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=root;Host=postgres_db;Port=5432;Database=RussianSpotify.API.Data"
      ConnectionStrings__RedisConnection: "redis:6379"
      MinioS3__MinioClient: "RussianSpotify"
      MinioS3__AccessKey: "russianSpotifyMinio"
      MinioS3__SecretKey: "russianSpotifyMinioPassword"
      MinioS3__ServiceUrl: "minio:9000"
      MinioS3__BucketName: "russian-spotify"
      EmailSettings__FromName: "RussianSpotify"
      EmailSettings__EmailAddress: "s1chess@yandex.ru"
      EmailSettings__Password: "qsmylcfruascxvhi"
      EmailSettings__SMTPServerHost: "smtp.yandex.ru"
      EmailSettings__SMTPServerPort: "465"
    ports:
      - "8080:80"
    networks:
      - russianspotify_network

volumes:
  minio_data:
  postgres_data:

networks:
  russianspotify_network:
    driver: bridge
