# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  main_project:
    build:
      context: "C:\\Users\\Админ\\Desktop\\.NET\\RussianSpotify\\RussianSpotify.Backend"
      dockerfile: "RussianSpotify.API.WEB/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RussianSpotify.API.WEB.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "russianspotify.api.web:dev"
    ports: []
    volumes:
    - "C:\\Users\\Админ\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\Админ\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Админ\\Desktop\\.NET\\RussianSpotify\\RussianSpotify.Backend\\RussianSpotify.API.WEB:/app:rw"
    - "C:\\Users\\Админ\\Desktop\\.NET\\RussianSpotify\\RussianSpotify.Backend:/src:rw"
    working_dir: "/app"
