apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-data
  name: rabbitmq-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
