name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    
    - name: Build the docker compose
      run: docker compose build

    - name: Push docker compose images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-compose
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy backend on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: docker compose up --pull -d
        
